
export const productsData = {
  Tablet: {
    products: [
      {
        _id: 1,
        ProductName: "AEFEN-P",
        ImageUrl: "/productImages/1.jpeg",
        Mrp: 100,
        Packing: `10 * 10`,
        Description: "Pain reliever and fever reducer",
        Category: "Tablet",
        Composition: "Aceclofenac 100mg + Paracetamol 325mg"
      },
      {
        _id: 2,
        ProductName: "AEFEN-MR",
        ImageUrl: "/productImages/2.jpeg",
        Mrp: 150,
        Packing: `10 * 10`,
        Description: "Blood thinner and pain reliever",
        Category: "Tablet",
        Composition: "Aceclofenac 100mg + Paracetamol 325mg + Chlorozoxazoe 250mg",
      },
      {
        _id: 3,
        ProductName: "AEFEN-SP",
        ImageUrl: "/productImages/3.jpeg",
        Mrp: 150,
        Packing: `10 * 10`,
        Description: "Blood thinner and pain reliever",
        Category: "Tablet",
        Composition: "Aceclofenac 100mg + Paracetamol 325mg + Serratiopeptidase 15mg",
      },
      {
        _id: 4,
        ProductName: "AZISAP-250",
        ImageUrl: "/productImages/4.jpeg",
        Mrp: 150,
        Packing: `10 * 6`,
        Description: "Blood thinner and pain reliever",
        Category: "Tablet",
        Composition: "Azithromycin 250mg",
      },
      {
        _id: 5,
        ProductName: " AZISAP-500",
        ImageUrl: "/productImages/5.jpeg",
        Mrp: 150,
        Packing: `10 * 3`,
        Description: "Blood thinner and pain reliever",
        Category: "Tablet",
        Composition: " Azithromycin 500mg ",
      },
      {
        _id: 6,
        ProductName: "CALCISON",
        ImageUrl: "/productImages/6.jpeg",
        Mrp: 150,
        Packing: `10 * 3`,
        Description: "Blood thinner and pain reliever",
        Category: "Tablet",
        Composition: "Calcium Citrate 1000mg + Magnesium 100mg + Zinc 10mg + Vitamin D3 200 i.u.",
      },
      {
        _id: 7,
        ProductName: "Mercical",
        ImageUrl: "/productImages/7.jpeg",
        Mrp: 150,
        Packing: `15 * 10`,
        Description: "Blood thinner and pain reliever",
        Category: "Tablet",
        Composition: " Calcium Carbonate 1250mg + Vitamin D3 250 i.u.",
      },
      {
        _id: 8,
        ProductName: "DEFOSAP-6",
        ImageUrl: "/productImages/8.jpg",
        Mrp: 150,
        Packing: `10 * 10`,
        Description: "Blood thinner and pain reliever",
        Category: "Tablet",
        Composition: "Deflazacort 6mg",
      },
      {
        _id: 9,
        ProductName: "FEROSAP-XT",
        ImageUrl: "/productImages/9.jpeg",
        Mrp: 150,
        Packing: `10 * 10`,
        Description: "Blood thinner and pain reliever",
        Category: "Tablet",
        Composition: "Ferrous Ascorbate 100mg + Folic acid 1500mcg + Zinc 22.5mg",
      },
      {
        _id: 10,
        ProductName: "LEVOSAP-5",
        ImageUrl: "/productImages/10.jpeg",
        Mrp: 150,
        Packing: 10 * 10,
        Description: "Blood thinner and pain reliever",
        Category: "Tablet",
        Composition: "Levocetirizine 5mg",
      },
    ]
  },
  Capsule: {
    products: [
      {
        _id: 26,
        ProductName: "PRASON-DSR",
        ImageUrl: "/productImages/26.jpg",
        Mrp: 250,
        Packing: 10 * 10,
        Description: "Antibiotic for bacterial infections",
        Category: "Capsule",
        Composition: "Pantoprazole 40mg + Domperidone 30mg (SR)",
      },
      {
        _id: 27,
        ProductName: "RABESAP-DSR",
        ImageUrl: "/productImages/27.jpeg",
        Mrp: 300,
        Packing: 10 * 10,
        Description: " Rabeprazole 20mg + Domperidone 30mg (SR)",
        Category: "Capsule",
        Composition: "Rabeprazole 20mg + Domperidone 30mg(SR)",
      },
      {
        _id: 28,
        ProductName: " RABESAP-DSR ",
        ImageUrl: "/productImages/28.jpeg",
        Mrp: 300,
        Packing: 20 * 10,
        Description: "Fish oil supplement",
        Category: "Capsule",
        Composition: " Rabeprazole 20mg + Domperidone 30mg (SR)",
      },
      {
        _id: 29,
        ProductName: "Omisap-20",
        ImageUrl: "/productImages/29.jpeg",
        Mrp: 300,
        Packing: 10 * 10,
        Description: "Fish oil supplement",
        Category: "Capsule",
        Composition: "Omeprazole 20mg",
      },
      {
        _id: 30,
        ProductName: " Omisap-D",
        ImageUrl: "/productImages/30.jpeg",
        Mrp: 300,
        Packing: 10 * 10,
        Description: "Fish oil supplement",
        Category: "Capsule",
        Composition: " Omeprazole 20mg  + Domperidone 10mg",
      },
      {
        _id: 31,
        ProductName: "PRESAP",
        ImageUrl: "/productImages/31.jpeg",
        Mrp: 300,
        Packing: 10 * 10,
        Description: "Fish oil supplement",
        Category: "Capsule",
        Composition: "Prebiotic & Probotic with FOS ",
      },
      {
        _id: 32,
        ProductName: "ITRASAP-100",
        ImageUrl: "/productImages/32.jpeg",
        Mrp: 300,
        Packing: 10 * 4,
        Description: "Fish oil supplement",
        Category: "Capsule",
        Composition: "Itraconazole 100mg",
      },
    ]
  },
  Softgel: {
    products: [
      {
        _id: 36,
        ProductName: "NUTRISAP",
        ImageUrl: "/productImages/36.jpg",
        Mrp: 150,
        Packing: 10 * 10,
        Description: "Antioxidant supplement",
        Category: "Softgel",
        Composition: "Multivitamins + Multiminerals + Anioxidants",
      },
      {
        _id: 37,
        ProductName: " NUTRISAP-L",
        ImageUrl: "/productImages/37.jpeg",
        Mrp: 350,
        Packing: 10 * 10,
        Description: "Heart health supplement",
        Category: "Softgel",
        Composition: " Lycopene + Multivitamins + Multiminerals + Anioxidants ",
      },
      {
        _id: 38,
        ProductName: "CALCISON-K27",
        ImageUrl: "/productImages/38.jpeg",
        Mrp: 350,
        Packing: 10 * 1 * 10,
        Description: "Heart health supplement",
        Category: "Softgel",
        Composition: " Calcium Carbonate 500 mg + Calcitriol 0.25 mcg + Vitamin K-27 45 mcg + Methylcobalamin 1500 mcg + L-MethylFolate 800 MCG  + Magnesium 50 MG  + Zinc 7.5 MG ",
      },
      {
        _id: 39,
        ProductName: "SAPMAX-9G",
        ImageUrl: "/productImages/39.jpg",
        Mrp: 350,
        Packing: 10 * 1 * 10,
        Description: "Heart health supplement",
        Category: "Softgel",
        Composition: " Ginko Biloba + Grape Seed Ext. + Green Tea Ext. + Lycopene + Ginseng + Garlic Powder + Guggle Ext. +  Multivitamin + Multimineral + Antioxidant",
      },
      {
        _id: 40,
        ProductName: "SAPBOL-AL",
        ImageUrl: "/productImages/40.jpeg",
        Mrp: 350,
        Packing: 10 * 1 * 10,
        Description: "Heart health supplement",
        Category: "Softgel",
        Composition: " Methylcobalamin 1500mcg + Alpha Lipoic Acid 100mg + Pyridoxine Hcl 3mg + Thiamine Hcl 10MG + Folic Acid 1.5mg ",
      },
      {
        _id: 41,
        ProductName: "CALCISON",
        ImageUrl: "/productImages/41.jpg",
        Mrp: 350,
        Packing: 10 * 10,
        Description: "Heart health supplement",
        Category: "Softgel",
        Composition: "Calcitriol 0.25 mg + Calcium Citrate 500mg + Magnesium 50mg + Zinc 7.5mg",
      },
    ]
  },
  Syrup: {
    products: [
      {
        _id: 46,
        ProductName: "COFSON",
        ImageUrl: "/productImages/46.jpeg",
        Mrp: 180,
        Packing: `100ml`,
        Description: "Cough suppressant",
        Category: "Syrup",
        Composition: " Ambroxol 15mg + Guaiphenesin 50mg + Terbutaline 1.25mg + Menthol 2.5mg ",
      },
      {
        _id: 47,
        ProductName: "COFSON-L ",
        ImageUrl: "/productImages/47.jpeg",
        Mrp: 250,
        Packing: `100ml`,
        Description: "Iron supplement",
        Category: "Syrup",
        Composition: " Levosalbutamol 1mg + Ambroxol 30mg + Guaiphenesin 50mg ",
      },
      {
        _id: 48,
        ProductName: " COFSON-D",
        ImageUrl: "/productImages/48.jpeg",
        Mrp: 250,
        Packing: `100ml`,
        Description: "Iron supplement",
        Category: "Syrup",
        Composition: " Dextromethaorphan HBr. 10mg + Chlorpheniramine Maleate 2mg + Phenylephrine Hcl 5mg ",
      },
      {
        _id: 49,
        ProductName: "FEROSAP",
        ImageUrl: "/productImages/49.jpeg",
        Mrp: 250,
        Packing: `200ml`,
        Description: "Iron supplement",
        Category: "Syrup",
        Composition: " Ferrous Ascorbate  + Folic acid + Zinc ",
      },
      {
        _id: 50,
        ProductName: " NUTRISAP",
        ImageUrl: "/productImages/50.jpeg",
        Mrp: 250,
        Packing: `200ml`,
        Description: "Iron supplement",
        Category: "Syrup",
        Composition: " Multivitamin + Multimineral + Antioxidant ",
      },
      {
        _id: 51,
        ProductName: " NUTRISAP-L",
        ImageUrl: "/productImages/51.jpeg",
        Mrp: 250,
        Packing: `200ml`,
        Description: "Iron supplement",
        Category: "Syrup",
        Composition: " Lycopene + Multivitamin + Multimineral + Antioxidant ",
      },
      {
        _id: 52,
        ProductName: "ZYMESON",
        ImageUrl: "/productImages/52.jpg",
        Mrp: 250,
        Packing: `200ml`,
        Description: "Iron supplement",
        Category: "Syrup",
        Composition: " Fungal Diastase + Papain + Multivitamin Syrup ",
      },
      {
        _id: 53,
        ProductName: "GROWSAP",
        ImageUrl: "/productImages/53.jpeg",
        Mrp: 250,
        Packing: `200ml`,
        Description: "Iron supplement",
        Category: "Syrup",
        Composition: "Cyproheptadine + Tricholine Citrate + Sorbitol",
      },
      {
        _id: 54,
        ProductName: "CALCISON",
        ImageUrl: "/productImages/54.jpeg",
        Mrp: 250,
        Packing: 200,
        Description: "Iron supplement",
        Category: "Syrup",
        Composition: " Calcium Carbonate 615mg + Magnesium 180mg + Zinc 2mg + Vitamin D3 200 i.u. ",
      },
    ]
  },
  Injection: {
    products: [
      {
        _id: 66,
        ProductName: "CALCISON-D3",
        ImageUrl: "/productImages/66.jpeg",
        Mrp: 500,
        Packing: `5 * 1ml`,
        Description: "Cholecalciferol-6 Lac i.u.",
        Category: "Injection",
        Composition: " Cholecalciferol-6 Lac i.u.",
      },
    ]
  },
  Paediatrics: {
    products: [
      {
        _id: 76,
        ProductName: "SAPCLAV-228.5",
        ImageUrl: "/productImages/76.jpeg",
        Mrp: 120,
        Packing: `30ml`,
        Description: "Fever reducer for children",
        Category: "Paediatrics",
        Composition: " Amoxycillin 200mg + Potassium Clavulanate 28.5mg",
      },
      {
        _id: 77,
        ProductName: " SAPCLAV-457",
        ImageUrl: "/productImages/77.jpg",
        Mrp: 250,
        Packing: `30ml`,
        Description: "Complete vitamin supplement for children",
        Category: "paediatrics",
        Composition: " Amoxycillin 400mg + Potassium Clavulanate 57mg ",
      },
      {
        _id: 78,
        ProductName: "MEFSAP-P",
        ImageUrl: "/productImages/78.jpeg",
        Mrp: 250,
        Packing: `60ml`,
        Description: "Complete vitamin supplement for children",
        Category: "Paediatrics",
        Composition: " Mefenamic 50mg + Paracetamol 125 mg ",
      },
      {
        _id: 79,
        ProductName: "MEFSAP-PLUS",
        ImageUrl: "/productImages/79.jpeg",
        Mrp: 250,
        Packing: `60ml`,
        Description: "Complete vitamin supplement for children",
        Category: "Paediatrics",
        Composition: " Mefenamic 100mg + Paracetamol 250 mg ",
      },
    ]
  },
  Ointments: {
    products: [
      {
        _id: 86,
        ProductName: "SAPGESIC-GEL",
        ImageUrl: "/productImages/86.jpeg",
        Mrp: 250,
        Packing: `30gm`,
        Description: "Complete vitamin supplement for children",
        Category: "Ointment",
        Composition: "Diclofenac Diethylamine 1.16% + Methyl Salicyclate 10% + Linseed Oil 5%  + Menthol Gel 5% + Capsaicin 0.025%",
      },
      {
        _id: 87,
        ProductName: "KETOSAP-PLUS",
        ImageUrl: "/productImages/87.jpg",
        Mrp: 250,
        Packing: `15gm`,
        Description: "Complete vitamin supplement for children",
        Category: "Ointment",
        Composition: "Ketoconazole 2% + Neomycin + Clobetasol 0.05% + Iodochlorhydroxyquinoline 1% + Tolnaftate 1% + Neomycin 0.10%",
      },
    ]
  },
  Ayurvedic: {
    products: [
      {
        _id: 96,
        ProductName: "PLATOSAP",
        ImageUrl: "/productImages/96.jpeg",
        Mrp: 250,
        Packing: `10*1*10`,
        description: "Complete vitamin supplement for children",
        Category: "Ayurvedic",
        Composition: "Carica Papaya 1100 mg + Giloy 400 mg + Goat Milk Powder 100mg + Kiwi Fruit Extract 50mg"
      },
      {
        _id: 97,
        ProductName: "LIVSAP",
        ImageUrl: "/productImages/97.jpeg",
        Mrp: 250,
        Packing: `200ml`,
        description: "Complete vitamin supplement for children",
        Category: "Ayurvedic",
        Composition: "Liver Tonic With Enzyme",
      },
      {
        _id: 98,
        ProductName: "FEMISAP",
        ImageUrl: "/productImages/98.jpeg",
        Mrp: 250,
        Packing: `200 ml`,
        description: "Complete vitamin supplement for children",
        Category: "Ayurvedic",
        Composition: "Uterine Tonic",
      },
      {
        _id: 99,
        ProductName: "SONTUSS",
        ImageUrl: "/productImages/99.jpeg",
        Mrp: 250,
        Packing: `100 ml`,
        description: "Complete vitamin supplement for children",
        Category: "Ayurvedic",
        Composition: " Honey Based Herbal Cough Syrup ",
      },
    ]
  }
};


