export const productsData = {
    tablet: {
      products: [
        {
          productName: "Paracetamol",
          imageUrl: "/images/products/paracetamol.png",
          mrp: 100,
          packing: 10,
          description: "Pain reliever and fever reducer",
          category: "tablet",
          salt: "Paracetamol",
        },
        {
          productName: "Aspirin",
          imageUrl: "/images/products/aspirin.png",
          mrp: 150,
          packing: 15,
          description: "Blood thinner and pain reliever",
          category: "tablet",
          salt: "Acetylsalicylic acid",
        },
        {
          productName: "Ibuprofen",
          imageUrl: "/images/products/ibuprofen.png",
          mrp: 120,
          packing: 20,
          description: "Anti-inflammatory and pain reliever",
          category: "tablet",
          salt: "Ibuprofen",
        },
        {
          productName: "Cetirizine",
          imageUrl: "/images/products/cetirizine.png",
          mrp: 80,
          packing: 10,
          description: "Antihistamine for allergies",
          category: "tablet",
          salt: "Cetirizine",
        },
        {
          productName: "Omeprazole",
          imageUrl: "/images/products/omeprazole.png",
          mrp: 200,
          packing: 14,
          description: "Acid reflux treatment",
          category: "tablet",
          salt: "Omeprazole",
        },
      ]
    },
    capsule: {
      products: [
        {
          productName: "Amoxicillin",
          imageUrl: "/images/products/amoxicillin.png",
          mrp: 250,
          packing: 12,
          description: "Antibiotic for bacterial infections",
          category: "capsule",
          salt: "Amoxicillin",
        },
        {
          productName: "Omega-3",
          imageUrl: "/images/products/omega3.png",
          mrp: 300,
          packing: 30,
          description: "Fish oil supplement",
          category: "capsule",
          salt: "Fish Oil",
        },
        {
          productName: "Vitamin D3",
          imageUrl: "/images/products/vitamind3.png",
          mrp: 180,
          packing: 60,
          description: "Vitamin D supplement",
          category: "capsule",
          salt: "Cholecalciferol",
        },
        {
          productName: "Gabapentin",
          imageUrl: "/images/products/gabapentin.png",
          mrp: 280,
          packing: 20,
          description: "Nerve pain medication",
          category: "capsule",
          salt: "Gabapentin",
        },
        {
          productName: "Fluoxetine",
          imageUrl: "/images/products/fluoxetine.png",
          mrp: 220,
          packing: 28,
          description: "Antidepressant medication",
          category: "capsule",
          salt: "Fluoxetine",
        },
      ]
    },
    softgel: {
      products: [
        {
          productName: "Vitamin E",
          imageUrl: "/images/products/vitamine.png",
          mrp: 150,
          packing: 30,
          description: "Antioxidant supplement",
          category: "softgel",
          salt: "Tocopherol",
        },
        {
          productName: "CoQ10",
          imageUrl: "/images/products/coq10.png",
          mrp: 350,
          packing: 30,
          description: "Heart health supplement",
          category: "softgel",
          salt: "Coenzyme Q10",
        },
        {
          productName: "Evening Primrose",
          imageUrl: "/images/products/primrose.png",
          mrp: 200,
          packing: 60,
          description: "Women's health supplement",
          category: "softgel",
          salt: "Evening Primrose Oil",
        },
        {
          productName: "Lutein",
          imageUrl: "/images/products/lutein.png",
          mrp: 280,
          packing: 30,
          description: "Eye health supplement",
          category: "softgel",
          salt: "Lutein",
        },
        {
          productName: "Fish Oil",
          imageUrl: "/images/products/fishoil.png",
          mrp: 220,
          packing: 90,
          description: "Heart and brain health supplement",
          category: "softgel",
          salt: "Fish Oil",
        },
      ]
    },
    syrup: {
      products: [
        {
          productName: "Cough Syrup",
          imageUrl: "/images/products/coughsyrup.png",
          mrp: 180,
          packing: 100,
          description: "Cough suppressant",
          category: "syrup",
          salt: "Dextromethorphan",
        },
        {
          productName: "Iron Tonic",
          imageUrl: "/images/products/irontonic.png",
          mrp: 250,
          packing: 200,
          description: "Iron supplement",
          category: "syrup",
          salt: "Ferrous Sulfate",
        },
        {
          productName: "Multivitamin Syrup",
          imageUrl: "/images/products/multivitamin.png",
          mrp: 300,
          packing: 200,
          description: "Complete vitamin supplement",
          category: "syrup",
          salt: "Multiple Vitamins",
        },
        {
          productName: "Zinc Syrup",
          imageUrl: "/images/products/zinc.png",
          mrp: 150,
          packing: 100,
          description: "Immunity booster",
          category: "syrup",
          salt: "Zinc Sulfate",
        },
        {
          productName: "Calcium Syrup",
          imageUrl: "/images/products/calcium.png",
          mrp: 200,
          packing: 200,
          description: "Bone health supplement",
          category: "syrup",
          salt: "Calcium Carbonate",
        },
      ]
    },
    injection: {
      products: [
        {
          productName: "Insulin",
          imageUrl: "/images/products/insulin.png",
          mrp: 500,
          packing: 1,
          description: "Diabetes medication",
          category: "injection",
          salt: "Human Insulin",
        },
        {
          productName: "B12 Shot",
          imageUrl: "/images/products/b12.png",
          mrp: 300,
          packing: 1,
          description: "Vitamin B12 supplement",
          category: "injection",
          salt: "Cyanocobalamin",
        },
        {
          productName: "Testosterone",
          imageUrl: "/images/products/testosterone.png",
          mrp: 600,
          packing: 1,
          description: "Hormone replacement",
          category: "injection",
          salt: "Testosterone Cypionate",
        },
        {
          productName: "Growth Hormone",
          imageUrl: "/images/products/growthhormone.png",
          mrp: 1000,
          packing: 1,
          description: "Growth hormone therapy",
          category: "injection",
          salt: "Somatropin",
        },
        {
          productName: "Epinephrine",
          imageUrl: "/images/products/epinephrine.png",
          mrp: 400,
          packing: 1,
          description: "Emergency allergy treatment",
          category: "injection",
          salt: "Epinephrine",
        },
      ]
    },
    paediatrics: {
      products: [
        {
          productName: "Children's Paracetamol",
          imageUrl: "/images/products/kidparacetamol.png",
          mrp: 120,
          packing: 100,
          description: "Fever reducer for children",
          category: "paediatrics",
          salt: "Paracetamol",
        },
        {
          productName: "Kids Multivitamin",
          imageUrl: "/images/products/kidsvitamin.png",
          mrp: 250,
          packing: 200,
          description: "Complete vitamin supplement for children",
          category: "paediatrics",
          salt: "Multiple Vitamins",
        },
        {
          productName: "Children's Cough Syrup",
          imageUrl: "/images/products/kidscough.png",
          mrp: 180,
          packing: 100,
          description: "Safe cough relief for children",
          category: "paediatrics",
          salt: "Dextromethorphan",
        },
        {
          productName: "Kids Probiotic",
          imageUrl: "/images/products/kidsprobiotic.png",
          mrp: 300,
          packing: 30,
          description: "Digestive health for children",
          category: "paediatrics",
          salt: "Multiple Strains",
        },
        {
          productName: "Children's Iron Drops",
          imageUrl: "/images/products/kidsirondrop.png",
          mrp: 200,
          packing: 30,
          description: "Iron supplement for children",
          category: "paediatrics",
          salt: "Ferrous Sulfate",
        },
      ]
    }
  };