export const productsData = {
  tablet: {
    products: [
      {
        _id: 1,
        productName: "Paracetamol",
        imageUrl: "/images/auth-dark.png",
        mrp: 100,
        packing: 10,
        description: "Pain reliever and fever reducer",
        category: "tablet",
        salt: "Paracetamol",
      },
      {
        _id: 2,
        productName: "Aspirin",
        imageUrl: "/images/auth-dark.png",
        mrp: 150,
        packing: 15,
        description: "Blood thinner and pain reliever",
        category: "tablet",
        salt: "Acetylsalicylic acid",
      },
      {
        _id: 3,
        productName: "Ibuprofen",
        imageUrl: "/images/auth-dark.png",
        mrp: 120,
        packing: 20,
        description: "Anti-inflammatory and pain reliever",
        category: "tablet",
        salt: "Ibuprofen",
      },
      {
        _id: 4,
        productName: "Cetirizine",
        imageUrl: "/images/auth-dark.png",
        mrp: 80,
        packing: 10,
        description: "Antihistamine for allergies",
        category: "tablet",
        salt: "Cetirizine",
      },
      {
        _id: 5,
        productName: "Omeprazole",
        imageUrl: "/images/auth-dark.png",
        mrp: 200,
        packing: 14,
        description: "Acid reflux treatment",
        category: "tablet",
        salt: "Omeprazole",
      },
    ]
  },
  capsule: {
    products: [
      {
        _id: 6,
        productName: "Amoxicillin",
        imageUrl: "/images/auth-dark.png",
        mrp: 250,
        packing: 12,
        description: "Antibiotic for bacterial infections",
        category: "capsule",
        salt: "Amoxicillin",
      },
      {
        _id: 7,
        productName: "Omega-3",
        imageUrl: "/images/auth-dark.png",
        mrp: 300,
        packing: 30,
        description: "Fish oil supplement",
        category: "capsule",
        salt: "Fish Oil",
      },
      {
        _id: 8,
        productName: "Vitamin D3",
        imageUrl: "/images/auth-dark.png",
        mrp: 180,
        packing: 60,
        description: "Vitamin D supplement",
        category: "capsule",
        salt: "Cholecalciferol",
      },
      {
        _id: 9,
        productName: "Gabapentin",
        imageUrl: "/images/auth-dark.png",
        mrp: 280,
        packing: 20,
        description: "Nerve pain medication",
        category: "capsule",
        salt: "Gabapentin",
      },
      {
        _id: 10,
        productName: "Fluoxetine",
        imageUrl: "/images/auth-dark.png",
        mrp: 220,
        packing: 28,
        description: "Antidepressant medication",
        category: "capsule",
        salt: "Fluoxetine",
      },
    ]
  },
  softgel: {
    products: [
      {
        _id: 11,
        productName: "Vitamin E",
        imageUrl: "/images/auth-dark.png",
        mrp: 150,
        packing: 30,
        description: "Antioxidant supplement",
        category: "softgel",
        salt: "Tocopherol",
      },
      {
        _id: 12,
        productName: "CoQ10",
        imageUrl: "/images/auth-dark.png",
        mrp: 350,
        packing: 30,
        description: "Heart health supplement",
        category: "softgel",
        salt: "Coenzyme Q10",
      },
      {
        _id: 13,
        productName: "Evening Primrose",
        imageUrl: "/images/auth-dark.png",
        mrp: 200,
        packing: 60,
        description: "Women's health supplement",
        category: "softgel",
        salt: "Evening Primrose Oil",
      },
      {
        _id: 14,
        productName: "Lutein",
        imageUrl: "/images/auth-dark.png",
        mrp: 280,
        packing: 30,
        description: "Eye health supplement",
        category: "softgel",
        salt: "Lutein",
      },
      {
        _id: 15,
        productName: "Fish Oil",
        imageUrl: "/images/auth-dark.png",
        mrp: 220,
        packing: 90,
        description: "Heart and brain health supplement",
        category: "softgel",
        salt: "Fish Oil",
      },
    ]
  },
  syrup: {
    products: [
      {
        _id: 16,
        productName: "Cough Syrup",
        imageUrl: "/images/auth-dark.png",
        mrp: 180,
        packing: 100,
        description: "Cough suppressant",
        category: "syrup",
        salt: "Dextromethorphan",
      },
      {
        _id: 17,
        productName: "Iron Tonic",
        imageUrl: "/images/auth-dark.png",
        mrp: 250,
        packing: 200,
        description: "Iron supplement",
        category: "syrup",
        salt: "Ferrous Sulfate",
      },
      {
        _id: 18,
        productName: "Multivitamin Syrup",
        imageUrl: "/images/auth-dark.png",
        mrp: 300,
        packing: 200,
        description: "Complete vitamin supplement",
        category: "syrup",
        salt: "Multiple Vitamins",
      },
      {
        _id: 19,
        productName: "Zinc Syrup",
        imageUrl: "/images/auth-dark.png",
        mrp: 150,
        packing: 100,
        description: "Immunity booster",
        category: "syrup",
        salt: "Zinc Sulfate",
      },
      {
        _id: 20,
        productName: "Calcium Syrup",
        imageUrl: "/images/auth-dark.png",
        mrp: 200,
        packing: 200,
        description: "Bone health supplement",
        category: "syrup",
        salt: "Calcium Carbonate",
      },
    ]
  },
  injection: {
    products: [
      {
        _id: 21,
        productName: "Insulin",
        imageUrl: "/images/auth-dark.png",
        mrp: 500,
        packing: 1,
        description: "Diabetes medication",
        category: "injection",
        salt: "Human Insulin",
      },
      {
        _id: 22,
        productName: "B12 Shot",
        imageUrl: "/images/auth-dark.png",
        mrp: 300,
        packing: 1,
        description: "Vitamin B12 supplement",
        category: "injection",
        salt: "Cyanocobalamin",
      },
      {
        _id: 23,
        productName: "Testosterone",
        imageUrl: "/images/auth-dark.png",
        mrp: 600,
        packing: 1,
        description: "Hormone replacement",
        category: "injection",
        salt: "Testosterone Cypionate",
      },
      {
        _id: 24,
        productName: "Growth Hormone",
        imageUrl: "/images/auth-dark.png",
        mrp: 1000,
        packing: 1,
        description: "Growth hormone therapy",
        category: "injection",
        salt: "Somatropin",
      },
      {
        _id: 25,
        productName: "Epinephrine",
        imageUrl: "/images/auth-dark.png",
        mrp: 400,
        packing: 1,
        description: "Emergency allergy treatment",
        category: "injection",
        salt: "Epinephrine",
      },
    ]
  },
  paediatrics: {
    products: [
      {
        _id: 26,
        productName: "Children's Paracetamol",
        imageUrl: "/images/auth-dark.png",
        mrp: 120,
        packing: 100,
        description: "Fever reducer for children",
        category: "paediatrics",
        salt: "Paracetamol",
      },
      {
        _id: 27,
        productName: "Kids Multivitamin",
        imageUrl: "/images/auth-dark.png",
        mrp: 250,
        packing: 200,
        description: "Complete vitamin supplement for children",
        category: "paediatrics",
        salt: "Multiple Vitamins",
      },
      {
        _id: 28,
        productName: "Children's Cough Syrup",
        imageUrl: "/images/auth-dark.png",
        mrp: 180,
        packing: 100,
        description: "Safe cough relief for children",
        category: "paediatrics",
        salt: "Dextromethorphan",
      },
      {
        _id: 29,
        productName: "Kids Probiotic",
        imageUrl: "/images/auth-dark.png",
        mrp: 300,
        packing: 30,
        description: "Digestive health for children",
        category: "paediatrics",
        salt: "Multiple Strains",
      },
      {
        _id: 30,
        productName: "Children's Iron Drops",
        imageUrl: "/images/auth-dark.png",
        mrp: 200,
        packing: 30,
        description: "Iron supplement for children",
        category: "paediatrics",
        salt: "Ferrous Sulfate",
      },
    ]
  }
};